language: android
jdk: oraclejdk7
android:
  components:
    - build-tools-20.0.0

env:
  - TNOODLE_INSTALL_GWT=1 ANDROID_TARGET=android-19

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python3
  - sudo apt-get install npm
  - (cd git-tools; npm install -d)
script:
  - ./tmt lint -a
  - ./tmt make dist -p wca
  - ./tmt make check
